# name: Deploy Website

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Ruby
#         uses: actions/setup-ruby@v1
#         with:
#           ruby-version: 2.x # Change to your desired Ruby version

#       - name: Install Dependencies
#         run: |
#           gem install bundler
#           bundle config path vendor/bundle
#           bundle install --jobs 4 --retry 3

#       - name: Install mermaid.cli
#         run: npm install -g mermaid.cli

#       - name: Set up deploy options
#         id: setup
#         run: |
#           git config --global user.name "GitHub Action"
#           git config --global user.email "your-email@example.com"

#           if [[ "${{ github.ref }}" = "refs/pull/*/merge" ]]; then
#             echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
#             echo "::set-output name=NO_PUSH::--no-push"
#           elif [[ "${{ github.ref }}" = "refs/heads/*" ]]; then
#             echo "::set-output name=SRC_BRANCH::${{ github.ref }}"
#           fi
#           echo "::set-output name=DEPLOY_BRANCH::gh-pages"

#       - name: Fix permission
#         run: |
#           chmod a+x bin/*
#           git commit -am "add execute permission to bin/deploy"

#       - name: Build website
#         run: npm run build

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: website
#           path: path/to/website/folder

#       - name: Deploy website
#         run: yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} --src ${{ steps.setup.outputs.SRC_BRANCH }} --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}





# # name: deploy

# # on:
# #   push:
# #     branches:
# #       - master
# #       - main
# #   pull_request:
# #     branches:
# #       - master
# #       - main
# #   workflow_dispatch:

# # permissions:
# #   contents: write

# # jobs:
# #   deploy:
# #     # available images: https://github.com/actions/runner-images#available-images
# #     runs-on: ubuntu-latest
# #     steps:
# #     - name: Checkout 🛎️
# #       uses: actions/checkout@v3
# #     - name: Setup Ruby
# #       uses: ruby/setup-ruby@v1
# #       with:
# #         ruby-version: '3.2.2'
# #         bundler-cache: true
# #     - name: Install and Build 🔧
# #       run: |
# #         pip3 install --upgrade jupyter
# #         npm install -g mermaid.cli
# #         export JEKYLL_ENV=production
# #         bundle exec jekyll build
# #     - name: Deploy 🚀
# #       if: github.event_name != 'pull_request'
# #       uses: JamesIves/github-pages-deploy-action@v4
# #       with:
# #         folder: _site

# # deploy.yml:

# # path: vendor/bundle

# # config.yml:

# # key: ${{ runner.os }}-gems-${{ hashFiles (***/Gemfile.lock') }}

# # restore-keys: |

# # ${{ runner.os }}-gems-

# # name: Install deps

# # run: 1

# # gem install bundler

# # bundle config path vendor/bundle

# # bundle install --jobs 4 --retry 3 

# # npm install -g mermaid.cli

# # name: Setup deploy options

# # id: setup

# # run: |

# # git config --global user.name "GitHub Action"

# # git config --global user.email "41898282+github-actions [bot]@users.noreply.gith

# # if [[ ${GITHUB_REF) = refs/pull/*/merge ]]; then # pull request

# # echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"

# # echo "::set-output name=NO_PUSH: :--no-push"

# # elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc

# # echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"

# # fi

# # echo "::set-output name=DEPLOY_BRANCH::gh-pages"

# # - name: Fix permission

# # run: |

# # chmod a+x bin/*

# # git commit -am "add execute permision to bin/deploy"

# # # Add the following lines

# # - name: Build website

# # run: npm run build

# # - name: Upload artifacts

# # uses: actions/upload-artifact@v2

# # with:

# # name: website

# # path: path/to/website/folder

# # - name: Deploy website

# # run: yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} --src ${{ steps.setup.outputs.SRC_BRANCH }} --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
name: deploy

on:
  push:
    branches:
      - master
      - source
  pull_request:
    branches:
      - master
      - source
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  repository-projects: write
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: Install deps
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
          echo "::set-output name=NO_PUSH::--no-push"
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"
        fi
        if [[ ${{ github.repository }} = *.github.io ]]; then # user/org repo
          echo "::set-output name=DEPLOY_BRANCH::master"
        else
          echo "::set-output name=DEPLOY_BRANCH::gh-pages"
        fi

    - name: Deploy website
      run:  yes | bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }}
                    --src ${{ steps.setup.outputs.SRC_BRANCH }}
                    --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}